### ISSUE TITLE
uncaught exception Reddit returned a 404 for user history

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/context-mod#31] opened 2021-10-20 22:45 UTC
```
2021-10-20T22:43:49+00:00 warn   : ~u/username~ {r/subreddit} [COM ID] [CHK low xp comment spam] Running rules failed due to uncaught exception Reddit returned a 404 for user history. Likely this user is shadowbanned.
SimpleError: Reddit returned a 404 for user history. Likely this user is shadowbanned.
    at Object.getAuthorActivities (CWD/src/Utils/SnoowrapUtils.js:92:19)
    at async cacheVal.cache.wrap.ttl (CWD/src/Subreddit/SubredditResources.js:340:24)
```

**Comment by FoxxMD** [comment] 2022-03-14 16:49
Newer versions of CM now include "blameable" stack traces which show "caused by" traces so, while this will still produce a stack trace, it should be easier to understand what happened and why it happened. Also, it should still be an error since the event/rule didn't run due to the history 404 being "unexpected", IMO. 

going to close this for now, if you think I should change the behavior we can re-open it and discuss.

**Closed by FoxxMD** 2022-03-14 16:49 UTC
